"use client";
import { useState } from "react";
import { CheckCircle2, LogOut, Moon, Save, Sun } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { Card } from "@/src/components/ui/card";
import { Input } from "@/src/components/ui/input";
export default function Settings(){const [saved,setSaved]=useState(false);return <div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase text-tangerine">Workspace</p><h1 className="mt-1 text-3xl font-semibold text-navy">Settings</h1><p className="mt-2 text-sm text-stone">Manage your profile and workspace preferences.</p><div className="mt-7 space-y-5"><Card className="p-5 sm:p-6"><Section title="Profile" copy="Used for workspace activity and notifications."/><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="field-label">Full name<Input defaultValue="Harsh Patel"/></label><label className="field-label">Email address<Input type="email" defaultValue="harsh@example.com"/></label></div><Button className="mt-5" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2500)}}>{saved?<><CheckCircle2 size={16}/>Saved</>:<><Save size={16}/>Save profile</>}</Button></Card><Card className="p-5 sm:p-6"><Section title="API status" copy="Current connection to your PolicyPal analysis backend."/><div className="mt-5 flex items-center justify-between rounded-md border border-navy/10 bg-surface p-4"><div><p className="text-sm font-semibold text-navy">Analysis service</p><p className="mt-1 text-xs text-stone">FastAPI · local environment</p></div><span className="ready-pill">Connected</span></div></Card><Card className="p-5 sm:p-6"><Section title="Preferences" copy="Choose how PolicyPal behaves in this browser."/><div className="mt-5 divide-y divide-navy/10"><SettingRow title="Appearance" copy="Light theme is optimized for document review"><div className="flex rounded-md bg-surface p-1"><button className="theme-option active"><Sun size={15}/>Light</button><button className="theme-option"><Moon size={15}/>Dark</button></div></SettingRow><SettingRow title="Analysis complete" copy="Notify me when a long analysis finishes"><input type="checkbox" defaultChecked className="h-5 w-5 accent-[#fe8005]"/></SettingRow><SettingRow title="Weekly summary" copy="Receive a weekly workspace digest"><input type="checkbox" className="h-5 w-5 accent-[#fe8005]"/></SettingRow></div></Card><Card className="flex flex-col items-start justify-between gap-4 border-red/15 p-5 sm:flex-row sm:items-center sm:p-6"><div><h2 className="font-semibold text-navy">Sign out of PolicyPal</h2><p className="mt-1 text-sm text-stone">You can sign back in at any time.</p></div><Button variant="danger"><LogOut size={16}/>Log out</Button></Card></div></div>}
function Section({title,copy}:{title:string;copy:string}){return <div><h2 className="text-lg font-semibold text-navy">{title}</h2><p className="mt-1 text-sm text-stone">{copy}</p></div>}
function SettingRow({title,copy,children}:{title:string;copy:string;children:React.ReactNode}){return <div className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-semibold text-navy">{title}</p><p className="mt-1 text-xs text-stone">{copy}</p></div>{children}</div>}
