"use client";
import { useRef, useState } from "react";
import { AlertCircle, CheckCircle2, FileText, Link2, LoaderCircle, Send, UploadCloud, X } from "lucide-react";
import { analyzeDocument, analyzeUpload } from "@/src/services/policy-api";
import { Button } from "@/src/components/ui/button";
import { Card } from "@/src/components/ui/card";
import { Input,Textarea } from "@/src/components/ui/input";

export function Analyzer(){
 const [mode,setMode]=useState<"url"|"file">("url"); const [url,setUrl]=useState("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"); const [file,setFile]=useState<File|null>(null); const [question,setQuestion]=useState("What text is contained in this document?"); const [answers,setAnswers]=useState<string[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const input=useRef<HTMLInputElement>(null);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setAnswers([]);const questions=question.split("\n").map(q=>q.trim()).filter(Boolean);if(!questions.length){setError("Add at least one question.");return}if(mode==="url"&&!url.trim()){setError("Add a document URL.");return}if(mode==="file"&&!file){setError("Choose a PDF, DOCX, or EML document to upload.");return}if(file&&file.size>20*1024*1024){setError("The selected document exceeds the 20 MB upload limit.");return}setLoading(true);try{const data=mode==="file"?await analyzeUpload(file!,questions):await analyzeDocument({documents:url.trim(),questions});setAnswers(data.answers)}catch(err){setError(err instanceof Error?err.message:"Analysis failed.")}finally{setLoading(false)}}
 return <div id="ask" className="grid scroll-mt-24 gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(330px,.9fr)]"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase text-stone">New analysis</p><h2 className="mt-1 text-xl font-semibold text-navy">Ask your document</h2></div><div className="flex rounded-md bg-surface p-1"><button onClick={()=>setMode("url")} className={`flex h-8 items-center gap-1.5 rounded px-2.5 text-xs font-semibold ${mode==="url"?"bg-white text-navy shadow-sm":"text-stone"}`}><Link2 size={14}/>URL</button><button onClick={()=>setMode("file")} className={`flex h-8 items-center gap-1.5 rounded px-2.5 text-xs font-semibold ${mode==="file"?"bg-white text-navy shadow-sm":"text-stone"}`}><UploadCloud size={14}/>Upload</button></div></div>
 <form onSubmit={submit} className="mt-6 space-y-5">{mode==="url"?<label className="block"><span className="mb-2 block text-sm font-semibold text-navy">Document URL</span><Input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/policy.pdf"/></label>:<div><input ref={input} type="file" accept=".pdf,.docx,.eml" className="hidden" onChange={e=>{const selected=e.target.files?.[0]||null;setFile(selected);setError("")}}/><button type="button" onClick={()=>input.current?.click()} className="flex min-h-40 w-full flex-col items-center justify-center rounded-md border border-dashed border-navy/25 bg-surface px-5 text-center hover:border-tangerine"><UploadCloud className="text-tangerine"/><p className="mt-3 max-w-full truncate text-sm font-semibold text-navy">{file?file.name:"Choose a document"}</p><p className="mt-1 text-xs text-stone">{file?`${(file.size/1024/1024).toFixed(2)} MB · Click to replace`:"PDF, DOCX, or EML · Maximum 20 MB"}</p></button></div>}
 <label className="block"><span className="mb-2 block text-sm font-semibold text-navy">Questions <span className="font-normal text-stone">· one per line</span></span><Textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about your document..."/></label>
 {error&&<div role="alert" className="flex items-start gap-2 rounded-md border border-red/20 bg-red/5 p-3 text-sm text-red"><AlertCircle className="mt-0.5 shrink-0" size={16}/>{error}<button type="button" onClick={()=>setError("")} className="ml-auto" aria-label="Dismiss error"><X size={15}/></button></div>}
 <Button type="submit" disabled={loading} className="w-full sm:w-auto">{loading?<><LoaderCircle className="animate-spin" size={17}/>Analyzing document</>:<>Analyze document<Send size={16}/></>}</Button></form></Card>
 <Card className="min-h-[420px] overflow-hidden"><div className="border-b border-navy/10 px-5 py-4"><p className="text-xs font-bold uppercase text-stone">Results</p></div>{loading?<div className="space-y-4 p-5" aria-label="Loading analysis"><div className="h-5 w-24 animate-pulse rounded bg-navy/8"/><div className="h-8 w-3/4 animate-pulse rounded bg-navy/8"/><div className="mt-6 h-24 animate-pulse rounded bg-navy/5"/><div className="h-16 animate-pulse rounded bg-navy/5"/></div>:answers.length?<div className="p-5">{answers.map((answer,i)=><article key={i} className="border-b border-navy/10 pb-6 last:border-0"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-xs font-bold text-[#17603a]"><CheckCircle2 size={15}/>Answer {i+1}</span><span className="rounded-full bg-[#eaf7ef] px-2 py-1 text-[10px] font-bold text-[#17603a]">Grounded response</span></div><p className="mt-4 leading-7 text-ink">{answer}</p><div className="mt-5 rounded-md border-l-2 border-tangerine bg-[#fff8ee] p-3 text-xs text-stone">Generated from the clauses retrieved in your uploaded document.</div></article>)}</div>:<div className="flex min-h-[350px] flex-col items-center justify-center px-8 text-center"><span className="grid h-12 w-12 place-items-center rounded-lg bg-[#fff3e4] text-tangerine"><FileText size={22}/></span><h3 className="mt-4 font-semibold text-navy">Your analysis will appear here</h3><p className="mt-2 max-w-xs text-sm leading-6 text-stone">Choose a document, ask a precise question, and PolicyPal will surface the answer.</p></div>}</Card></div>
}
